#--- Site ---
name: "Your site name"
description: "Your site description"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl: ""
siteurl: "http://localhost"
#--- siteurl: "http://192.168.1.100"
email: "your_email@email.com"
# disqus: ""
# mailchimp-list: ""

include: ["_pages"]
permalink: /:year/:month/:day/:title/

#--- Plugins ---
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-regex-replace

authors:
    First Last:
      name:     First Last
      site:     https://your_site.com
      avatar:   assets/images/avatar.png
      email:    your_email@email.com
      twitter:  https://twitter.com/your_twitter

    sal:
      name:           Sal
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Sal, the author of Mundana, the theme you're currently previewing. I hope you like it!"
      email:          wowthemesnet@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    jane:
      name:           Jane
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet
 
#--- Defaults ---
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: First Last
      avatar: /assets/images/avatar.png

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

#--- Syntax ---
markdown: kramdown
highlighter: rouge

#--- Paginate-v2 ---
pagination:
    enabled: true
    offset: 1
    per_page: 8
    indexpage: index
    sort_reverse: true
    trail:
        before: 3
        after:  3
    debug: true


#--- Custom localization variables ---
# Polyglot does not work well with Paginate-v2
# define these two variables instead
locales: [en, it]
default_locale: en

#--- Atom feed ---
feed:
    excerpt_only: false
    icon: /assets/images/favicon.ico
    feed_items: 10
    feed_update_period: daily
    feed_update_frequency: 1

#--- HTML compression ---
compress_html:
    clippings: []
    comments: all
    startings: []
    endings: []
    ignore:
    envs: []
    blanklines: true
    profile: false

#--- Comma comments ---
commentserver: https://localhost:5888

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules, TODO]
